blogs/urls.py
from django.conf.urls import url

from .views import blog_list, create_blog, blog_detail, blog_delete

urlpatterns = [

    url(r'^list/', blog_list, name='list'),
    url(r'^create/', create_blog, name='create'),
    url(r'^detail/(?P<pk>\d+)$', blog_detail, name='detail'),
   # url(r'^update/(?P<pk>\d+)$', TweetUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)$',blog_delete, name='delete'),

]

loginproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^tweets/', include('tweets.urls', namespace='tweets')),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
]

tweets/urls.py
from django.conf.urls import url

from .views import TweetListView, TweetDeleteView, TweetDetailView, TweetCreateView, TweetUpdateView

urlpatterns = [

    url(r'^list/', TweetListView.as_view(), name='list'),
    url(r'^create/', TweetCreateView.as_view(), name='create'),
    url(r'^detail/(?P<pk>\d+)$', TweetDetailView.as_view(), name='detail'),
    url(r'^update/(?P<pk>\d+)$', TweetUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)$', TweetDeleteView.as_view(), name='delete'),

]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=160)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

tweets/models.py
from django.db import models

# Create your models here.

class Tweet(models.Model):
    tweets = models.TextField(max_length=140)
    timestamp  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.tweets

blogs/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = [
            'title',
            'content',
        ]

blogs/views.py
from django.shortcuts import render,reverse
from django.http import HttpResponseRedirect

from .models import Blog
from .forms import BlogForm

# Create your views here.

def blog_list(request):
    queryset = Blog.objects.all()
    context = {
        'object_list': queryset,
    }

    return render(request, 'blogs/blog_list.html', context)


def create_blog(request):
    if not request.user.is_authenticated():
        return reverse('login')
    form = BlogForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return HttpResponseRedirect('/blogs/list')

    context = {
        'form': form,
    }

    return render(request, 'blogs/create.html', context)

def blog_detail(request, pk=None):
    instance = Blog.objects.get(pk=pk)
    context = {
        'object': instance,
    }

    return render(request, 'blogs/detail.html', context)

def blog_delete(request,pk=None):
    instance=Blog.objects.get(pk=pk)
    
    context= {
        'object': instance,
    }

    return render(request,'blogs/delete.html',context)

tweets/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Tweet


# Create your views here.

class TweetListView(ListView):
    model = Tweet
    queryset = Tweet.objects.all()
    template_name = 'tweets/tweet_list.html'


class TweetDetailView(DetailView):
    model = Tweet
    template_name = 'tweets/tweet_detail.html'


class TweetDeleteView(DeleteView):
    model = Tweet
    template_name = 'tweets/delete.html'

    def get_success_url(self):
        return reverse('tweets:list')


class TweetUpdateView(UpdateView):
    model = Tweet
    fields = [
        'tweets',
    ]
    template_name = 'tweets/update.html'

    def get_success_url(self):
        return reverse('tweets:list')


class TweetCreateView(CreateView):
    model = Tweet
    fields = [
        'tweets',
    ]
    template_name = 'tweets/create.html'

    def get_success_url(self):
        return reverse('tweets:list')














        # def tweet_list(request):
        #     object_list = Tweet.objects.all()
        #     context = {
        #         'object_list': object_list
        #     }
        #
        #     return render(request, 'tweets/tweet_list.html', context)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">

    <link type="text/css" rel="stylesheet" href="css/style.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


</head>

<body>

<nav>
    <div class="nav-wrapper teal lighten-2">
       {% if request.user.is_authenticated %}
             <a href="{% url 'home' %}">HOME</a>
            {% endif %}
        <a href="#" class="brand-logo center">MY TWITTER</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if request.user.is_authenticated %}
            <li><a href="#">{{ request.user.username }}</a></li>
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

{% if request.user.is_authenticated %}
            <div class="container">
            <div class="row">
                <div class="col s12 m6">
                    <li><a href="{% url 'tweets:list' %}">List tweets</a></li>
                    <li><a href="{% url 'tweets:create' %}">Create tweets</a></li>
                    <li><a href="{% url 'blogs:list' %}">List blogs</a></li>
                    <li><a href="{% url 'blogs:create' %}">Create blogs</a></li>
                </div>
                <div class="col s12 m6">
                    <div class="container center">
                        <img src="http://ordinaryquotes.com/images/21456/xw7_download_attitude_bo.jpg" class="rounded" alt="...">
                     </div>
                </div>
            </div>
            </div>
            {% endif %}
{% block content %}

{% endblock %}




<footer class="page-footer teal lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer
                    content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
    </div>
</footer>


<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
<script type="text/javascript" src="js/script.js"></script>
</body>
</html>

templates/blogs/blog_list.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    {% for object in object_list %}
        <div class="row">
            <div class="col s6 offset-s3">
                <h4>{{ object.title }}</h4>
                <p>{{ object.content }}</p>
                <a href="{%  url 'blogs:detail' object.pk %}">Details</a>
                
                <a href="{%  url 'blogs:delete' object.pk %}">Delete</a>
                <hr>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/blogs/create.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <input type="submit" class="btn" value="Create Blog">
    </form>
{% endblock %}

templates/blogs/delete.html
{% extends 'base.html' %}

{% block title %}
Delete Blog
{% endblock %}


{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure want to delete this blog?</p>
        <input type="submit" class="btn" value="Delete">
    </form>

{% endblock %}

templates/blogs/detail.html
{% extends 'base.html' %}

{% block content %}
    {{ object.title }}
    {{ object.content }}
{% endblock %}

templates/tweets/create.html
{% extends 'base.html' %}

{% block title %}
Create Tweet
{% endblock %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input class="btn" type="submit" value="Create Tweet">
    </form>
{% endblock %}

templates/tweets/delete.html
{% extends 'base.html' %}

{% block title %}
Delete Tweet
{% endblock %}


{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure want to delete this tweet?</p>
        <input type="submit" class="btn" value="Delete">
    </form>

{% endblock %}

templates/tweets/tweet_detail.html
{% extends 'base.html' %}

{% block title %}
Tweet Detail
{% endblock %}


{% block content %}

    <p>Tweet Detail</p>
    {{ object.tweets }}
{% endblock %}

templates/tweets/tweet_list.html
{% extends 'base.html' %}

{% block title %}
Tweet List
{% endblock %}

{% block content %}
{% for object in object_list %}

    <p>{{ object.tweets }}</p>
    <a href="{% url 'tweets:detail' object.pk %}">detail</a>
    <a href="{% url 'tweets:update' object.pk %}">update</a>
    <a href="{% url 'tweets:delete' object.pk %}">delete</a>

    {% endfor %}
{% endblock %}

templates/tweets/update.html
{% extends 'base.html' %}

{% block title %}
Create Tweet
{% endblock %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Update Tweet">
    </form>
{% endblock %}